plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: "pages-themes/cayman@v0.2.0"

title: "Rhododendron Research Network"
description: "Documentation and projects for the R-RN"

author:
  name: Alan Elliott
  email: aelliott@rbge.org.uk

collections:
  taxa:
    output: true
    permalink: \taxa\:slug\

feed:
  path: feed.xml
  collections:
    - taxa

force_rebuild: true
