plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: "pages-themes/cayman@v0.2.0"

title: "Rhododendron Research Network"
description: "Documentation and projects for the R-RN"

author:
  name: Alan Elliott
  email: aelliott@rbge.org.uk

# REQUIRED: tell Jekyll where collections live
collections_dir: .

collections:
  rrn_taxa:
    output: true
    permalink: /taxa/:slug/

# REQUIRED: include non-underscore folder
include:
  - rrn_taxa

feed:
  path: feed.xml
  collections:
    - rrn_taxa

#force_rebuild: true