plugins:
  # add remote-theme plugin
  - jekyll-remote-theme

# Use remote-theme plugin to load `minima` repository. But first, ensure the `theme` key is disabled.
# theme: minima
remote_theme: "jekyll/minima"

minima:
  skin: classic
  header_pages:
    - projects.md
    - checklist.md
    - publications.md
    
title: "Rhododendron Research Network"
description: "Documentation and projects for the R-RN"
author:
  name: Alan Elliott
  email: aelliott@rbge.org.uk
#exclude:
 # - taxa

  #
# header_pages:
#  - projects.md
#  - checklist.md
#  - publication.md
