plugins:
  # add remote-theme plugin
  - jekyll-feed
  - jekyll-remote-theme

# Use remote-theme plugin to load `minima` repository. But first, ensure the `theme` key is disabled.
# theme: minima
remote_theme: "jekyll/minima"

minima:
  skin: classic
  nav_pages:
    - projects.md
    - checklist.md
    - publications.md
    - coc.md
    
title: "Rhododendron Research Network"
description: "Documentation and projects for the R-RN"
author:
  name: Alan Elliott
  email: aelliott@rbge.org.uk
source: docs
collections:
  taxa:
    output: true
    permalink: /taxa/:slug/
feed:
  path: feed.xml
  collections:
    - taxa

  
  #
# header_pages:
#  - projects.md
#  - checklist.md
#  - publication.md
